### ISSUE TITLE
remove "graduate school usa" from university "funding sector"

### ISSUE THREAD

**Issue by melteng** [Datawheel/datausa-site#114]
see /cip/520206/ for example. Two University of Phoenix campuses have a (colorless) funding sector attribute.

![screenshot 2015-12-14 11 22 18](https://cloud.githubusercontent.com/assets/8160651/11786975/812159c8-a257-11e5-9a24-0213a1dd1a05.png)

**Comment by davelandry** [comment]
"Graduate School USA" is an actual university name, and the colorless part is due to #128
