### ISSUE TITLE
national data should use 1-year ACS estimates

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datausa-site#32]
- [x] yg
 - [x] yg_income_distribution
 - [x] yg_poverty_race
 - [x] yg_nativity_age
 - [x] yg_race
 - [x] ygl_speakers
 - [x] yg_conflict
 - [x] yg_property_value
 - [x] yg_property_tax
 - [x] yg_vehicles
 - [x] yg_travel_time
 - [x] yg_transport

**Comment by alexandersimoes** [comment]
- [ ] yg
 - [ ] ygo
 - [ ] yg_med_earnings
 - [ ] yg_income
    - [ ] US
    - [ ] States
 - [ ] yg_income_distribution
 - [ ] yg_poverty_race
 - [ ] ygi_num_emp
 - [ ] ygi_med_earnings
 - [ ] yg_nativity_age
 - [ ] yg_race
 - [ ] ygl_speakers
 - [ ] yg_conflict
 - [ ] yg_property_value
 - [ ] yg_property_tax
 - [ ] yg_vehicles
 - [ ] yg_travel_time
 - [ ] yg_transport

**Comment by davelandry** [comment]
@alexandersimoes, I moved your checklist into the initial comment, as I think that's the only way to get the progress bar to appear in the full issue list :sunglasses:

**Comment by alexandersimoes** [comment]
tudo bem :+1:

**Comment by alexandersimoes** [comment]
YGO / YGI will now come from PUMs
