### ISSUE TITLE
incorrect number formatting

### ISSUE THREAD

**Issue by danielbyler** [Datawheel/datausa-site#71]
http://beta.datausa.io/profile/cip/2705/#skills 

5.00000000001 shouldn't be on the legend

![image](https://cloud.githubusercontent.com/assets/3857364/11719698/f315a4de-9f29-11e5-8bd8-eccfea6b38dc.png)

**Comment by davelandry** [comment]
Also visible in some axes:
http://beta.datausa.io/profile/cip/4005/demographics/degree_obtainment/
![screen shot 2015-12-15 at 12 05 47 pm](https://cloud.githubusercontent.com/assets/1847581/11817725/3e22760c-a324-11e5-844d-f5034ca1ab77.png)
