### ISSUE TITLE
Plurality, not majority

### ISSUE THREAD

**Issue by danielbyler** [Datawheel/datausa-site#78]
http://beta.datausa.io/profile/geo/04000US42/ 

This chart states 'the majority' of households. I think you mean plurality but sometimes it could be a majority. Everywhere we make a 'majority' statement in the text, could we compute the percent the top category is of the whole sample and filter to 'plurality' or 'majority' accordingly? Also, since we're calculating percentages anyway, can we display the percentages for all charts in the tooltip where the Y axis is a count and the chart is supposed to refer to the whole population (as opposed to those charts which are 'top 5' charts). 

![image](https://cloud.githubusercontent.com/assets/3857364/11746173/ac4cd790-9fea-11e5-9747-8fc31c2b7497.png)

**Comment by davelandry** [comment]
Thanks for the clarification on the grammar. We'll try to get this hooked up, but is it safe to assume that "plurality" is correct in all cases?

Here's a separate issue about getting the "share" into most visualizations: #21

**Comment by danielbyler** [comment]
No, sorry. Plurality has a specific meaning which is the mode but not the majority. :(

**Comment by danielbyler** [comment]
You could say 'largest share'. That would be correct no matter what.

**Comment by davelandry** [comment]
:beers:
