### ISSUE TITLE
Special character in search

### ISSUE THREAD

**Issue by danielbyler** [Datawheel/datausa-site#82]
Searching %% gives me this: http://beta.datausa.io/search/?q=%%

I'm stopping my attempts to see what special characters do until this is resolved. 

![image](https://cloud.githubusercontent.com/assets/3857364/11747307/7a3d03e6-9ff0-11e5-81c8-84a8802ebc04.png)

**Comment by jspeis** [comment]
Looks like an error is occurring in Javascript when trying to parse out the url parameters with %:

Uncaught URIError: URI malformed getURLParameter @ ?q=%%:377(anonymous function) @ ?q=%%:464

  function getURLParameter(name) {
    return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search)||[,""])[1].replace(/\+/g, '%20'))||null
  }
