### ISSUE TITLE
potential duplicate data in acs.ygo_num_emp

### ISSUE THREAD

**Issue by davelandry** [Datawheel/datausa-site#85]
take a look at the duplicate occupation ids:
http://nightly-api.datausa.io/api/?sort=desc&sumlevel=county%2C4&limit=5&show=geo%2Cacs_occ&year=latest&required=num_emp%2Cnum_emp_moe%2Cnum_emp_rca&geo=05000US25025&order=num_emp

**Comment by alexandersimoes** [comment]
FIXED!
